/UrControlGuiRos2ParamProvider:
  ros__parameters:
    use_sim_time: false
    gui_window_x: 72
    gui_window_y: 27
    gui_window_width: 1848
    gui_window_height: 1053
    robot_ip: "192.168.1.102"
    robot_interface_port: 30003