/UrControlGuiRos2ParamProvider:
  ros__parameters:
    use_sim_time: false
    gui_window_x: 0
    gui_window_y: 0
    gui_window_width: 1920
    gui_window_height: 1080
    robot_ip: "0.0.0.0"
    robot_interface_port: 30002