/RoboCleanerGuiRos2ParamProvider:
  ros__parameters:
    use_sim_time: false
    gui_window_x: 72
    gui_window_y: 27
    gui_window_width: 1848
    gui_window_height: 1053
    # suppported levelIds - 1, 2, 3
    level_id: 2
    use_fog_of_war: True