/RoboCollectorControllerRos2ParamProvider:
  ros__parameters:
    use_sim_time: false
    gui_window_x: 1272
    gui_window_y: 527
    gui_window_width: 648
    gui_window_height: 553
    use_local_controller_mode: True
    user: not_set
    repository: not_set
    commit_sha: not_set